// Complete dummy data extracted from the provided medical report
export const dummyData = {
  meta: {
    refNumber: "PH25 - 317",
    gpName: "Dr. Aanya Sharma",
    gpAddress: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    clientName: "Aarav Singh",
    clientAddress: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardianName: "Isha Singh",
    contactNumber: "+91 98123-45678",
    assessmentDate: "2024-08-14",
    assessmentTime: "10:00",
    assessmentLocation: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
  },
  stage1: {
    refNumber: "PH25 - 317",
    gpName: "Dr. Aanya Sharma",
    gpAddress: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    clientName: "Aarav Singh",
    clientAddress: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardianName: "Isha Singh",
    contactNumber: "+91 98123-45678",
    assessmentDate: "2024-08-14",
    assessmentTime: "10:00",
    assessmentLocation: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
    introNotes: "Initial telephone intake conducted on 09.04.25 with both parents present, followed by clinical evaluation on 07.05.25.",
    present: ["mother"],
    presentOther: "",
    ccReport: "Parents of Aarav Singh\nDr. Meera Nair, Consultant Paediatric Neurologist, Sunrise Hospital, Anna Salai, Chennai\nPaediatric Cardiology Dept, Sunrise Hospital, Anna Salai, Chennai",
    handedness: "right",
    age: "10 years, 11 months",
    schoolYear: "Class 4",
    school: "Vidya Mandir Bengaluru",
    referralBackground: "Thank you for referring Aarav (right-handed, 10 years, 11 months, currently in Class 4 at Vidya Mandir Bengaluru) for an ADHD assessment. The referral was initiated following concerns expressed both by Aarav's parents and his class teacher about persistent difficulties with attention, organisation, and regulation of activity level. These difficulties have been observed across home and school environments for over two academic years. The presenting concerns first became apparent during Aarav's transition to formal schooling in Class 1, when his teacher Ms. Lakshmi Patel noted significant challenges with sustained attention during structured learning activities. Despite his evident intellectual curiosity and verbal abilities, Aarav consistently struggled to complete age-appropriate tasks within expected timeframes. His teacher reported that he would frequently become distracted by environmental stimuli, including sounds from adjacent classrooms, movement in the corridor, or even minor changes in lighting conditions. These attentional difficulties were compounded by notable restlessness, with Aarav finding it challenging to remain seated during circle time, story sessions, or individual work periods. The concerns intensified in Class 2 when academic demands increased, and organisational expectations became more complex. His teacher, Mr. Rajesh Kumar, documented frequent instances of incomplete assignments, despite Aarav demonstrating understanding of the material when assessed verbally. The pattern of difficulties persisted through Class 3 under the guidance of Ms. Priya Menon, who noted that Aarav's challenges were not attributable to intellectual limitations but rather seemed to stem from fundamental difficulties with attention regulation and impulse control. At home, Aarav's parents initially attributed his behaviours to typical childhood exuberance and high energy levels. However, as his younger brothers Rohan and Kabir developed, it became increasingly apparent that Aarav's patterns of behaviour were qualitatively different and more persistent than typical developmental variations. His mother, Isha, began to recognise similarities between Aarav's behaviours and her own childhood experiences, particularly following her recent ADHD diagnosis. The family's relocation from northern India to Bengaluru in 2011 had provided stability, but the transition to the local educational system highlighted cultural and linguistic adaptations that may have initially masked some of Aarav's underlying neurodevelopmental differences. Both parents work part-time, which has allowed for consistent observation of Aarav's behaviour patterns across different contexts and times of day. The decision to seek formal assessment was reached collaboratively between the family and school staff, with particular input from the school counsellor who had observed Aarav across multiple settings and interactions with various peers and adults.",
    medicalHistory: "Aarav's medical history begins with a generally uncomplicated neonatal period, though some early indicators may have foreshadowed later developmental patterns. During his first year, routine paediatric reviews consistently showed normal growth parameters and developmental milestones were achieved within or ahead of expected timeframes. However, from approximately 18 months of age, his parents began to notice patterns of increased activity levels and shorter sleep durations compared to peer norms, though these were initially considered within the range of normal variation. The onset of migraine headaches around 3.5 years of age marked the beginning of more significant medical concerns. These episodes initially presented as severe headaches accompanied by nausea, vomiting, and photophobia, causing considerable distress for both Aarav and his family. The frequency and intensity of these migraines required specialist consultation with Dr. Meera Nair, Consultant Paediatric Neurologist at Sunrise Hospital in Chennai. Initial investigations included detailed neurological examination and MRI scanning to rule out structural abnormalities, all of which returned normal results. The migraines were characterised by their episodic nature, typically lasting 2-4 hours and often associated with specific triggers including changes in sleep patterns, certain food additives, and periods of high stress or excitement. Management strategies implemented by Dr. Nair included lifestyle modifications focusing on regular sleep hygiene, dietary modifications to identify and avoid potential triggers, and the judicious use of age-appropriate analgesics during acute episodes. Over the subsequent three years, there has been a marked improvement in both frequency and severity of episodes, with Aarav now experiencing migraines approximately once every 2-3 months compared to the weekly episodes during the acute phase. The improvement has been attributed to a combination of maturation of his neurological systems, consistent application of preventive strategies, and possibly hormonal changes associated with pre-pubertal development. Iron deficiency was first identified during routine blood screening at age 4 years, presenting with mild fatigue and occasional pale complexion. Further investigation revealed low serum ferritin levels and mild microcytic anaemia, requiring initiation of oral iron supplementation. The deficiency was attributed to rapid growth phases combined with somewhat selective eating patterns typical of children with attention and sensory processing differences. Regular monitoring of iron status has continued, with periodic adjustments to supplementation dosages based on laboratory results and clinical presentation. Most recent assessments show improved iron stores, though ongoing supplementation remains necessary to maintain optimal levels. Aarav has demonstrated good tolerance of iron supplements when administered with food, and the family has been educated about iron-rich food sources to complement pharmaceutical intervention. No other significant medical conditions have been documented, and routine vaccinations have been completed according to the standard Indian immunisation schedule without adverse reactions.",
    medications: "Ibuprofen PRN for headaches. Triptan PRN for migraines. Iron supplementation (ongoing).",
    surgicalHistory: "No past surgical or procedural history documented.",
    allergies: "No known drug allergies.",
    forensicHistory: "No forensic history documented.",
    substanceHistory: "No substance use history.",
    householdComposition: "The Singh family relocated from northern India to Bengaluru in 2011. Aarav is the eldest of three boys: Rohan (7) and Kabir (2). His mother, Isha (36), works part-time as a receptionist in a wellness clinic. His father, Vihaan (39), works part-time as a chef in a hotel.",
    otherFamilyDetails: "Home environment is stable, though the family reports challenges in managing routines and discipline given the competing demands of three young children.",
    familyMedicalHistory: "Notable family history of cancer on both maternal and paternal sides including maternal grandfather (colon cancer at age 65), paternal aunt (breast cancer at age 42), and paternal grandfather (lung cancer, unknown age). Maternal grandmother has hypothyroidism managed with levothyroxine. Paternal grandmother has type 2 diabetes mellitus diagnosed at age 58. History of cardiovascular disease including paternal grandfather (myocardial infarction at age 70) and maternal uncle (hypertension from age 45). No known genetic disorders or significant neurological conditions in extended family apart from suspected learning difficulties.",
    familyMentalHealth: "Mother recently diagnosed with ADHD Combined Presentation at age 35, alongside a long-standing history of depression (onset postpartum after Aarav's birth) and generalised anxiety disorder. Mother reports childhood difficulties with attention and organisation that were never formally assessed. Father describes himself as having possible anxiety but has never sought assessment or treatment. Maternal aunt has bipolar disorder diagnosed in her twenties. Maternal uncle reported to have had significant depression during adolescence requiring hospitalisation. Paternal side reports 'nervousness' and 'worry' in several family members but no formal diagnoses. Mother also has a history of iron deficiency anaemia requiring ongoing supplementation.",
    familyLearningDifficulties: "Suspected (but undiagnosed) dyslexia in maternal uncle who struggled significantly with reading throughout school and continues to avoid written tasks as an adult. Maternal cousin reportedly received learning support in school for mathematics difficulties. Mother reports her own childhood difficulties with spelling and written expression that may represent undiagnosed learning differences. Father describes himself as a slow reader but attributes this to limited educational opportunities in his youth.",
    antenatalDetails: "Aarav was born full-term via spontaneous vaginal delivery, weighing approximately 3 kg. There were no antenatal complications, and his mother reported no tobacco, alcohol, or illicit drug use during pregnancy.",
    deliveryDetails: "Spontaneous vaginal delivery at full term. Birth weight approximately 3 kg. No complications during delivery.",
    postpartumDetails: "No postnatal complications were recorded.",
    developmentalMilestones: "Aarav's developmental trajectory has been characterised by a pattern of early achievement in several domains, with some areas showing more variable progression. Motor development commenced with early indicators of advanced gross motor skills, including sitting independently at 5.5 months, crawling at 7 months, and achieving independent walking at 10 months, placing him well ahead of typical developmental expectations. His early mobility was accompanied by notable fearlessness and physical confidence, with Aarav demonstrating advanced climbing, running, and jumping abilities throughout his toddler years. Parents report that he was consistently drawn to physical challenges and seemed to require higher levels of sensory input through movement and physical exploration compared to his peers. Fine motor development followed a more variable pattern, with adequate pincer grasp achieved by 12 months allowing for basic manipulation of small objects and finger foods. However, as precision requirements increased, particularly in relation to drawing, writing, and detailed manipulative tasks, some challenges became apparent. By 18 months, while Aarav could stack blocks and complete simple puzzles, his approach tended to be more impulsive and less methodical than typically observed. This pattern has persisted, with ongoing difficulties noted in tasks requiring sustained fine motor control, particularly handwriting and detailed artwork. Language development emerged as a clear area of strength, with first meaningful words appearing at 11 months, including 'mama', 'dada', and 'ball'. Two-word combinations developed by 15 months, and short sentences were evident by 18 months. His vocabulary expansion was rapid and extensive, with particular strengths in abstract and conceptual language. By age 4, Aarav was using complex sentence structures and demonstrating sophisticated understanding of grammatical rules, often correcting others' speech patterns. His verbal abilities have consistently exceeded age expectations, with particular strengths in storytelling, asking complex questions, and engaging in elaborate imaginative narratives. However, pragmatic language skills have shown some variability, with occasional difficulties in turn-taking during conversations and tendency to dominate discussions with topics of particular interest. Toilet training was initiated at 2.5 years with daytime continence achieved by 3 years following a period of consistent routine and positive reinforcement strategies. Nighttime continence took longer to establish, with occasional accidents continuing until age 4.5 years, which parents attributed to Aarav's deep sleep patterns and high fluid intake. Social-emotional development has shown a more complex pattern, with early attachment formation proceeding normally but with some difficulties becoming apparent during separation and transition periods. Separation anxiety extended beyond typical timeframes, with Aarav showing distress during preschool drop-offs until age 4. Peer interactions have been an area of ongoing development, with Aarav showing genuine interest in friendships but sometimes struggling with the social nuances required for successful peer relationships. His high energy levels and intense interests sometimes overwhelmed quieter children, while his verbal sophistication could intimidate same-age peers. Sleep patterns have consistently been challenging, with shorter sleep durations and longer sleep onset times noted from early infancy. Current sleep patterns include difficulty settling at bedtime, frequent night wakings, and early morning arousal, requiring ongoing management strategies.",
    additionalNotes: "Assessment process included direct observation, structured interviews, behavioural questionnaires (Conners-4), and collateral input from school staff.",
    assessments: {
      ot: false,
      otDetails: "",
      slt: false,
      sltDetails: "",
      cognitive: true,
      cognitiveDetails: "Comprehensive cognitive assessment completed by Dr. Raj Verma (Senior Educational Psychologist) on 12.05.25",
      other: false,
      otherAssessmentDetails: ""
    },
    nextSessionType: "In-person consultation",
    otherDetails: "Results reviewed jointly on 20.05.25"
  },
  stage2: {
    ref: "PH25 - 317",
    gp_name: "Dr. Aanya Sharma",
    gp_address: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    client_name: "Aarav Singh",
    client_address: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardian_name: "Isha Singh",
    assessment_date: "2024-08-14",
    assessment_time: "10:00",
    location_method: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
    previous_reminders: "Review cognitive assessment results from Dr. Raj Verma. Ensure parent questionnaires are completed.",
    intro_notes: "Clinical evaluation with Aarav and his mother. Direct observation and structured interviews conducted.",
    mse: [
      { task: "Months of the Year Backwards", yes: false, no: true, notes: "Unable to complete task accurately" },
      { task: "Serial Threes", yes: false, no: true, notes: "Significant difficulty with task" },
      { task: "Digit Span Forward", yes: true, no: false, notes: "Completed adequately for age" },
      { task: "Digit Span Reverse", yes: false, no: true, notes: "Struggled with reverse sequencing" },
      { task: "Verbal A Test", yes: true, no: false, notes: "Good performance on attention task" }
    ],
    mental_state_notes: "During clinic observation, Aarav presented as an alert and engaging child, with noticeable restlessness. He frequently shifted posture, tapped his feet, and manipulated objects in his hands. At times, he appeared to attempt self-regulation by sitting on his hands, though leg movements continued. Aarav was able to articulate his thoughts well and maintained appropriate eye contact intermittently. Notably, he demonstrated a tendency to avert gaze during verbal instructions, which he reported helped him 'listen better' by reducing distractions.",
    inattention: {
      "1": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently makes careless mistakes in schoolwork, particularly in mathematics and written assignments." },
      "2": { freq: true, impact: true, other: true, criteria: true, notes: "Difficulty sustaining attention during reading and written tasks. Requires frequent breaks." },
      "3": { freq: true, impact: true, other: false, criteria: true, notes: "Often appears not to listen when spoken to directly, described as 'dreamy' by teachers." },
      "4": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently rushes work, resulting in avoidable errors. Does not follow through on instructions." },
      "5": { freq: true, impact: true, other: true, criteria: true, notes: "Disorganisation: school bag and desk consistently messy, leading to misplaced items and incomplete homework submissions." },
      "6": { freq: true, impact: true, other: true, criteria: true, notes: "Avoids tasks requiring sustained mental effort, particularly homework and reading assignments." },
      "7": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently loses necessary items for school and home activities." },
      "8": { freq: true, impact: true, other: true, criteria: true, notes: "Easily distracted during meals and conversations by external stimuli." },
      "9": { freq: true, impact: true, other: true, criteria: true, notes: "Requires multiple reminders to complete simple tasks due to forgetfulness." }
    },
    hyperimpulsivity: {
      "1": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently fidgets, squirms, taps hands and feet during activities." },
      "2": { freq: true, impact: false, other: true, criteria: true, notes: "Difficulty remaining seated during appropriate times, particularly during meals and classroom activities." },
      "3": { freq: true, impact: true, other: true, criteria: true, notes: "Reported inner restlessness, unable to engage in quiet activities." },
      "4": { freq: true, impact: true, other: true, criteria: true, notes: "Unable to engage in play or leisure activities quietly." },
      "5": { freq: true, impact: true, other: true, criteria: true, notes: "Often described as being 'on the go' or 'driven by a motor'." },
      "6": { freq: true, impact: true, other: true, criteria: true, notes: "Talks excessively, sometimes disrupts group activities." },
      "7": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently interrupts others in conversation due to fear of forgetting his point." },
      "8": { freq: true, impact: true, other: true, criteria: true, notes: "Difficulty waiting his turn in games and conversations." },
      "9": { freq: true, impact: true, other: true, criteria: true, notes: "Interrupts or intrudes on others, particularly during group activities." }
    },
    other_difficulties: "Sleep onset difficulties are prominent, with Aarav typically taking 2–3 hours to fall asleep due to racing thoughts and inability to settle. Parents report he often gets up multiple times during the night, citing worries about school tasks or random thoughts. Bedtime routines are inconsistent due to his resistance to stopping preferred activities. Occasionally explosive reactions to perceived injustices, particularly when items are misplaced or when transitions are imposed without warning. These episodes can last 15-30 minutes and involve crying, shouting, and physical agitation. Hoards seemingly trivial objects including scraps of paper, old packaging, broken toys, and food wrappers, citing emotional 'memories' attached to them. Attempts to remove these items result in significant distress. Social difficulties include interrupting peers during conversations, difficulty reading social cues, and tendency to dominate group discussions with topics of special interest. Academic challenges extend beyond attention issues to include poor handwriting legibility, inconsistent mathematical computation despite good conceptual understanding, and extreme difficulty with written expression tasks. Fine motor skills appear adequate in isolation but deteriorate significantly when combined with cognitive demands.",
    comorbidities: "The hoarding behaviours may reflect an emerging obsessive-compulsive tendency, or may be related to executive function deficits including difficulty disengaging from ongoing activities and challenges with decision-making and categorisation. Given the family history of mental health conditions and the complexity of presentation, monitoring for developing anxiety disorders, mood dysregulation, and possible oppositional behaviours will be required. Sleep difficulties may represent a separate comorbid condition requiring specific intervention. The combination of ADHD symptoms with emerging obsessive-compulsive features suggests a complex neurodevelopmental profile that may benefit from multimodal intervention approaches. Consideration should be given to potential sensory processing differences given his reported need to manipulate objects and difficulty with certain textures and sounds in the environment.",
    other_notes: "Teacher's perspective: In a classroom of 33 students, Aarav's attentional difficulties are pronounced. Ms. Priya Menon described him as bright and capable, likely to perform well on standardised tests, but hindered by disorganisation and distractibility. Some concern about anxiety-driven behaviours, particularly the compulsive need to use the toilet at the start of lessons and during transitions.",
    preliminary_summary: "ADHD Combined Presentation (DSM-5)",
    ot: false,
    ot_details: "",
    slt: false,
    slt_details: "",
    cognitive: false,
    cognitive_details: "",
    other: true,
    other_details: "Monitor for emerging obsessive-compulsive behaviours",
    next_session_type: "Final assessment and feedback session",
    other_details_ns: "Review with parents and provide comprehensive management recommendations",
    careManager_reminders: "Discuss medication options and school-based interventions",
    personal_info: "Aarav enjoys building with Lego and is interested in space exploration",
    additional_notes: "Comprehensive behavioural assessment confirms persistent ADHD symptoms across multiple settings with significant functional impairment.",
    diagnostic_outcome: "ADHD Combined Presentation (DSM-5)"
  },
  stage3: {
    ref_number: "PH25 - 317",
    gp_name: "Dr. Aanya Sharma",
    gp_address: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    client_name_cc: "Aarav Singh",
    additional_doctors: "Dr. Meera Nair, Consultant Paediatric Neurologist, Sunrise Hospital, Anna Salai, Chennai\nPaediatric Cardiology Dept, Sunrise Hospital, Anna Salai, Chennai",
    client_name: "Aarav Singh",
    client_address: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardian_name: "Isha Singh",
    assessment_date: "2024-08-14",
    assessment_time: "10:00",
    location_method: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
    mse: [
      { task: "Months of the Year Backwards", yes: false, no: true, notes: "Continued difficulty with reverse sequencing tasks" },
      { task: "Serial Threes", yes: false, no: true, notes: "Unable to maintain concentration for mathematical sequencing" },
      { task: "Digit Span Forward", yes: true, no: false, notes: "Age-appropriate performance maintained" },
      { task: "Digit Span Reverse", yes: false, no: true, notes: "Consistent difficulty with working memory tasks" },
      { task: "Verbal A Test", yes: true, no: false, notes: "Good sustained attention to specific stimuli" }
    ],
    mental_state_details: "Consistent presentation with previous sessions. Aarav demonstrated good engagement but persistent restlessness and attention regulation difficulties. Self-regulation strategies (sitting on hands) noted but with limited effectiveness.",
    diagnosis: ["ADHD Combined Presentation (DSM - 5)"],
    other_diagnosis: "No additional diagnoses at this time. Monitor for emerging obsessive-compulsive features.",
    criteria: [
      "Criterion A: >6/9 symptoms in inattention and/or hyperactivity/impulsivity",
      "Criterion B: Symptoms were present before age 7/12",
      "Criterion C: Criteria are met in two or more settings",
      "Criterion D: Symptoms are causing impairment in social, academic, and home life"
    ],
    criteria_details: "Aarav's presentation meets DSM-5 criteria for ADHD Combined Presentation: Persistent symptoms of inattention and hyperactivity-impulsivity across multiple settings. Symptoms present before age 12. Clear functional impairment academically, socially, and at home.",
    plan_dx: ["Diagnosis of ADHD confirmed (14.08.2024)"],
    psychoeducation: [
      "Psycho-education on diagnosis & implications",
      "Pharmacological vs non-pharmacological interventions",
      "Need for routine/structure"
    ],
    med_investigations: {
      gp_followup: "Continue iron supplementation monitoring",
      bloods: false,
      bloods_details: "",
      ecg: false,
      ecg_details: "",
      other_med: true,
      other_med_details: "Monitor ferritin levels quarterly. Consider trial of stimulant medication under close monitoring for migraine exacerbation."
    },
    med_other_details: "Continue iron supplementation and monitor ferritin levels quarterly. Consider a trial of stimulant medication under close monitoring for migraine exacerbation.",
    allied: {
      ot: false,
      ot_details: "",
      slt: false,
      slt_details: "",
      educational: true,
      educational_details: "School-based interventions recommended"
    },
    allied_details: "Educational interventions: Preferential classroom seating away from high-traffic areas. Allow for movement breaks every 20–30 minutes. Use visual schedules and checklists for organisation.",
    aftercare_details: "I recommend review in 8 weeks to assess the effectiveness of school-based strategies and to consider initiation of medication if functional impairment persists. Parents are encouraged to liaise with the ADHD India Support Group for peer support and resources.",
    recommendations: "Medical: Consider a trial of stimulant medication under close monitoring for migraine exacerbation. Continue iron supplementation and monitor ferritin levels quarterly. Educational: Preferential classroom seating away from high-traffic areas. Allow for movement breaks every 20–30 minutes. Use visual schedules and checklists for organisation. Behavioural: Implement a home 'launch pad' area for essential school items. Use of object trackers ('Tiles') for frequently misplaced items. Consistent positive reinforcement for task completion. Sleep: Introduce a calming bedtime routine, use of white noise or audiobooks. Reduce screen exposure at least 60 minutes before bedtime.",
    additional_notes_final: "Family participation in ADHD India Support Group and Parent Education Programme strongly recommended. The Singh family would benefit from structured parent training focusing on behaviour management strategies, consistent routines, and understanding of ADHD symptom presentation. Daily Omega-3 supplementation (evidence-based moderate support for ADHD) should be initiated at 1000mg EPA/DHA daily. Written recommendations for school provided, focusing on classroom strategies including environmental modifications, academic accommodations, and individual support planning. Regular communication between home and school should be established through a daily communication book. Family therapy may be beneficial to address the impact of ADHD on family dynamics and sibling relationships. Ongoing monitoring of Aarav's emotional development and self-esteem will be important as he becomes more aware of his differences from peers. Consider referral to occupational therapy if fine motor coordination difficulties persist or worsen. Sleep hygiene education and possible sleep study referral if sleep difficulties do not improve with behavioural interventions. Review academic progress and consider educational psychology input for learning support if needed. Long-term monitoring for development of comorbid conditions including anxiety, depression, and learning disabilities will be necessary."
  },
  report: {},
  hourlyRate: 180
};