// Complete dummy data extracted from the provided medical report
export const dummyData = {
  meta: {
    refNumber: "PH25 - 317",
    gpName: "Dr. Aanya Sharma",
    gpAddress: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    clientName: "Aarav Singh",
    clientAddress: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardianName: "Isha Singh",
    contactNumber: "+91 98123-45678",
    assessmentDate: "2024-08-14",
    assessmentTime: "10:00",
    assessmentLocation: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
  },
  stage1: {
    refNumber: "PH25 - 317",
    gpName: "Dr. Aanya Sharma",
    gpAddress: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    clientName: "Aarav Singh",
    clientAddress: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardianName: "Isha Singh",
    contactNumber: "+91 98123-45678",
    assessmentDate: "2024-08-14",
    assessmentTime: "10:00",
    assessmentLocation: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
    introNotes: "Initial telephone intake conducted on 09.04.25 with both parents present, followed by clinical evaluation on 07.05.25.",
    present: ["mother"],
    presentOther: "",
    ccReport: "Parents of Aarav Singh\nDr. Meera Nair, Consultant Paediatric Neurologist, Sunrise Hospital, Anna Salai, Chennai\nPaediatric Cardiology Dept, Sunrise Hospital, Anna Salai, Chennai",
    handedness: "right",
    age: "10 years, 11 months",
    schoolYear: "Class 4",
    school: "Vidya Mandir Bengaluru",
    referralBackground: "Thank you for referring Aarav (right-handed, 10 years, 11 months, currently in Class 4 at Vidya Mandir Bengaluru) for an ADHD assessment. The referral was initiated following concerns expressed both by Aarav's parents and his class teacher about persistent difficulties with attention, organisation, and regulation of activity level. These difficulties have been observed across home and school environments for over two academic years.",
    medicalHistory: "Migraines: Onset around 3.5 years old, initially severe with vomiting, but markedly improved in the last two years. Managed under paediatric neurology review (Dr. Meera Nair). Iron deficiency: Documented in early childhood; requires ongoing supplementation. No known drug allergies.",
    medications: "Ibuprofen PRN for headaches. Triptan PRN for migraines. Iron supplementation (ongoing).",
    surgicalHistory: "No past surgical or procedural history documented.",
    allergies: "No known drug allergies.",
    forensicHistory: "No forensic history documented.",
    substanceHistory: "No substance use history.",
    householdComposition: "The Singh family relocated from northern India to Bengaluru in 2011. Aarav is the eldest of three boys: Rohan (7) and Kabir (2). His mother, Isha (36), works part-time as a receptionist in a wellness clinic. His father, Vihaan (39), works part-time as a chef in a hotel.",
    otherFamilyDetails: "Home environment is stable, though the family reports challenges in managing routines and discipline given the competing demands of three young children.",
    familyMedicalHistory: "Notable family history of cancer on both maternal and paternal sides. Maternal grandmother has hypothyroidism.",
    familyMentalHealth: "Mother recently diagnosed with ADHD, alongside a history of depression and anxiety. Mother also has a history of iron deficiency.",
    familyLearningDifficulties: "Suspected (but undiagnosed) dyslexia in a maternal uncle.",
    antenatalDetails: "Aarav was born full-term via spontaneous vaginal delivery, weighing approximately 3 kg. There were no antenatal complications, and his mother reported no tobacco, alcohol, or illicit drug use during pregnancy.",
    deliveryDetails: "Spontaneous vaginal delivery at full term. Birth weight approximately 3 kg. No complications during delivery.",
    postpartumDetails: "No postnatal complications were recorded.",
    developmentalMilestones: "Milestones were achieved early — walked at 10 months, first words before 12 months, and short sentences by 18 months. There were no gross or fine motor coordination concerns. Toilet training was achieved within the expected timeframe, and no regression in skills has been noted.",
    additionalNotes: "Assessment process included direct observation, structured interviews, behavioural questionnaires (Conners-4), and collateral input from school staff.",
    assessments: {
      ot: false,
      otDetails: "",
      slt: false,
      sltDetails: "",
      cognitive: true,
      cognitiveDetails: "Comprehensive cognitive assessment completed by Dr. Raj Verma (Senior Educational Psychologist) on 12.05.25",
      other: false,
      otherAssessmentDetails: ""
    },
    nextSessionType: "In-person consultation",
    otherDetails: "Results reviewed jointly on 20.05.25"
  },
  stage2: {
    ref: "PH25 - 317",
    gp_name: "Dr. Aanya Sharma",
    gp_address: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    client_name: "Aarav Singh",
    client_address: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardian_name: "Isha Singh",
    assessment_date: "2024-08-14",
    assessment_time: "10:00",
    location_method: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
    previous_reminders: "Review cognitive assessment results from Dr. Raj Verma. Ensure parent questionnaires are completed.",
    intro_notes: "Clinical evaluation with Aarav and his mother. Direct observation and structured interviews conducted.",
    mse: [
      { task: "Months of the Year Backwards", yes: false, no: true, notes: "Unable to complete task accurately" },
      { task: "Serial Threes", yes: false, no: true, notes: "Significant difficulty with task" },
      { task: "Digit Span Forward", yes: true, no: false, notes: "Completed adequately for age" },
      { task: "Digit Span Reverse", yes: false, no: true, notes: "Struggled with reverse sequencing" },
      { task: "Verbal A Test", yes: true, no: false, notes: "Good performance on attention task" }
    ],
    mental_state_notes: "During clinic observation, Aarav presented as an alert and engaging child, with noticeable restlessness. He frequently shifted posture, tapped his feet, and manipulated objects in his hands. At times, he appeared to attempt self-regulation by sitting on his hands, though leg movements continued. Aarav was able to articulate his thoughts well and maintained appropriate eye contact intermittently. Notably, he demonstrated a tendency to avert gaze during verbal instructions, which he reported helped him 'listen better' by reducing distractions.",
    inattention: {
      "1": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently makes careless mistakes in schoolwork, particularly in mathematics and written assignments." },
      "2": { freq: true, impact: true, other: true, criteria: true, notes: "Difficulty sustaining attention during reading and written tasks. Requires frequent breaks." },
      "3": { freq: true, impact: true, other: false, criteria: true, notes: "Often appears not to listen when spoken to directly, described as 'dreamy' by teachers." },
      "4": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently rushes work, resulting in avoidable errors. Does not follow through on instructions." },
      "5": { freq: true, impact: true, other: true, criteria: true, notes: "Disorganisation: school bag and desk consistently messy, leading to misplaced items and incomplete homework submissions." },
      "6": { freq: true, impact: true, other: true, criteria: true, notes: "Avoids tasks requiring sustained mental effort, particularly homework and reading assignments." },
      "7": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently loses necessary items for school and home activities." },
      "8": { freq: true, impact: true, other: true, criteria: true, notes: "Easily distracted during meals and conversations by external stimuli." },
      "9": { freq: true, impact: true, other: true, criteria: true, notes: "Requires multiple reminders to complete simple tasks due to forgetfulness." }
    },
    hyperimpulsivity: {
      "1": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently fidgets, squirms, taps hands and feet during activities." },
      "2": { freq: true, impact: false, other: true, criteria: true, notes: "Difficulty remaining seated during appropriate times, particularly during meals and classroom activities." },
      "3": { freq: true, impact: true, other: true, criteria: true, notes: "Reported inner restlessness, unable to engage in quiet activities." },
      "4": { freq: true, impact: true, other: true, criteria: true, notes: "Unable to engage in play or leisure activities quietly." },
      "5": { freq: true, impact: true, other: true, criteria: true, notes: "Often described as being 'on the go' or 'driven by a motor'." },
      "6": { freq: true, impact: true, other: true, criteria: true, notes: "Talks excessively, sometimes disrupts group activities." },
      "7": { freq: true, impact: true, other: true, criteria: true, notes: "Frequently interrupts others in conversation due to fear of forgetting his point." },
      "8": { freq: true, impact: true, other: true, criteria: true, notes: "Difficulty waiting his turn in games and conversations." },
      "9": { freq: true, impact: true, other: true, criteria: true, notes: "Interrupts or intrudes on others, particularly during group activities." }
    },
    other_difficulties: "Sleep onset difficulties, often taking 2–3 hours to fall asleep due to racing thoughts. Occasionally explosive reactions to perceived injustices (e.g., misplacing items). Hoards seemingly trivial objects (scraps of paper, old packaging) citing 'memories' attached to them.",
    comorbidities: "The hoarding behaviours may reflect an emerging obsessive-compulsive tendency, or may be related to executive function deficits (difficulty disengaging from ongoing activities and decision-making). This will require monitoring.",
    other_notes: "Teacher's perspective: In a classroom of 33 students, Aarav's attentional difficulties are pronounced. Ms. Priya Menon described him as bright and capable, likely to perform well on standardised tests, but hindered by disorganisation and distractibility. Some concern about anxiety-driven behaviours, particularly the compulsive need to use the toilet at the start of lessons and during transitions.",
    preliminary_summary: "ADHD Combined Presentation (DSM-5)",
    ot: false,
    ot_details: "",
    slt: false,
    slt_details: "",
    cognitive: false,
    cognitive_details: "",
    other: true,
    other_details: "Monitor for emerging obsessive-compulsive behaviours",
    next_session_type: "Final assessment and feedback session",
    other_details_ns: "Review with parents and provide comprehensive management recommendations",
    careManager_reminders: "Discuss medication options and school-based interventions",
    personal_info: "Aarav enjoys building with Lego and is interested in space exploration",
    additional_notes: "Comprehensive behavioural assessment confirms persistent ADHD symptoms across multiple settings with significant functional impairment.",
    diagnostic_outcome: "ADHD Combined Presentation (DSM-5)"
  },
  stage3: {
    ref_number: "PH25 - 317",
    gp_name: "Dr. Aanya Sharma",
    gp_address: "Lotus Medical Centre\nGreenfield Primary Care Centre\n55 Park Street\nBengaluru\n560001",
    client_name_cc: "Aarav Singh",
    additional_doctors: "Dr. Meera Nair, Consultant Paediatric Neurologist, Sunrise Hospital, Anna Salai, Chennai\nPaediatric Cardiology Dept, Sunrise Hospital, Anna Salai, Chennai",
    client_name: "Aarav Singh",
    client_address: "71 MG Road, Bengaluru, Karnataka",
    dob: "2013-09-17",
    guardian_name: "Isha Singh",
    assessment_date: "2024-08-14",
    assessment_time: "10:00",
    location_method: "PrimaHealth Clinic, Bengaluru",
    careManager: "Dr. Kabir Das",
    mse: [
      { task: "Months of the Year Backwards", yes: false, no: true, notes: "Continued difficulty with reverse sequencing tasks" },
      { task: "Serial Threes", yes: false, no: true, notes: "Unable to maintain concentration for mathematical sequencing" },
      { task: "Digit Span Forward", yes: true, no: false, notes: "Age-appropriate performance maintained" },
      { task: "Digit Span Reverse", yes: false, no: true, notes: "Consistent difficulty with working memory tasks" },
      { task: "Verbal A Test", yes: true, no: false, notes: "Good sustained attention to specific stimuli" }
    ],
    mental_state_details: "Consistent presentation with previous sessions. Aarav demonstrated good engagement but persistent restlessness and attention regulation difficulties. Self-regulation strategies (sitting on hands) noted but with limited effectiveness.",
    diagnosis: ["ADHD Combined Presentation (DSM - 5)"],
    other_diagnosis: "No additional diagnoses at this time. Monitor for emerging obsessive-compulsive features.",
    criteria: [
      "Criterion A: >6/9 symptoms in inattention and/or hyperactivity/impulsivity",
      "Criterion B: Symptoms were present before age 7/12",
      "Criterion C: Criteria are met in two or more settings",
      "Criterion D: Symptoms are causing impairment in social, academic, and home life"
    ],
    criteria_details: "Aarav's presentation meets DSM-5 criteria for ADHD Combined Presentation: Persistent symptoms of inattention and hyperactivity-impulsivity across multiple settings. Symptoms present before age 12. Clear functional impairment academically, socially, and at home.",
    plan_dx: ["Diagnosis of ADHD confirmed (14.08.2024)"],
    psychoeducation: [
      "Psycho-education on diagnosis & implications",
      "Pharmacological vs non-pharmacological interventions",
      "Need for routine/structure"
    ],
    med_investigations: {
      gp_followup: "Continue iron supplementation monitoring",
      bloods: false,
      bloods_details: "",
      ecg: false,
      ecg_details: "",
      other_med: true,
      other_med_details: "Monitor ferritin levels quarterly. Consider trial of stimulant medication under close monitoring for migraine exacerbation."
    },
    med_other_details: "Continue iron supplementation and monitor ferritin levels quarterly. Consider a trial of stimulant medication under close monitoring for migraine exacerbation.",
    allied: {
      ot: false,
      ot_details: "",
      slt: false,
      slt_details: "",
      educational: true,
      educational_details: "School-based interventions recommended"
    },
    allied_details: "Educational interventions: Preferential classroom seating away from high-traffic areas. Allow for movement breaks every 20–30 minutes. Use visual schedules and checklists for organisation.",
    aftercare_details: "I recommend review in 8 weeks to assess the effectiveness of school-based strategies and to consider initiation of medication if functional impairment persists. Parents are encouraged to liaise with the ADHD India Support Group for peer support and resources.",
    recommendations: "Medical: Consider a trial of stimulant medication under close monitoring for migraine exacerbation. Continue iron supplementation and monitor ferritin levels quarterly. Educational: Preferential classroom seating away from high-traffic areas. Allow for movement breaks every 20–30 minutes. Use visual schedules and checklists for organisation. Behavioural: Implement a home 'launch pad' area for essential school items. Use of object trackers ('Tiles') for frequently misplaced items. Consistent positive reinforcement for task completion. Sleep: Introduce a calming bedtime routine, use of white noise or audiobooks. Reduce screen exposure at least 60 minutes before bedtime.",
    additional_notes_final: "Family participation in ADHD India Support Group and Parent Education Programme recommended. Daily Omega-3 supplementation (evidence-based moderate support for ADHD). Written recommendations for school provided, focusing on classroom strategies and individual support."
  },
  report: {},
  hourlyRate: 180
};